export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const LOGOUT = 'LOGOUT';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_ERROR = 'FETCH_CHATS_ERROR';
export const FETCH_CHATS_LOADING = 'FETCH_CHATS_LOADING';
export const ADD_CHAT = 'ADD_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
export const ADD_USERS_TO_CHAT = 'ADD_USERS_TO_CHAT';
export const LEAVE_CHAT = 'LEAVE_CHAT';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const NEW_MESSAGE = 'NEW_MESSAGE';