export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const LOGOUT = 'LOGOUT';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_ERROR = 'FETCH_CHATS_ERROR';
export const FETCH_CHATS_LOADING = 'FETCH_CHATS_LOADING';